package xyz.view;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.*;

public class BoxFound extends JComponent implements Runnable {

    /**
     *
     * @author __USER__
     */
    /**
     * Creates new form Donttai
     */
    public BoxFound() {
        setLayout(null);
        setSize(999,999);
    }

    //String path = "E:\\Workspaces\\MyEclipse_9.0\\20120731\\bin\\动态图\\1\\10";
    //Java默认文件路径是项目的根目录，所以要手动加上bin及其以下的路径
    String path = "aa/";
    public static int idx=-1;
    public boolean isRunning=false;
    public void paint(Graphics g) {
        if (idx>=0) {
//        if (idx>=0) {
            ImageObserver imageObserver = new ImageObserver() {
                @Override
                public boolean imageUpdate(Image img, int infoflags, int x, int y,
                                           int width, int height) {
                    // TODO Auto-generated method stub
                    return false;
                }
            };
            try {
                //g.drawImage(ImageIO.read(new File(Donttai.class.getResource("1.png").toString())), 20, 20, imageObserver);
                String temp = "";
                if (idx <= 189)
                    temp = path + idx + ".png";
                g.drawImage(ImageIO.read(new File(temp)), 200, 270, 400, 300,
                        imageObserver);
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
//        }
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private javax.swing.JButton jButton1;

    @Override
    public void run() {
        // TODO Auto-generated method stub
        while (true) {
            repaint();
            if (idx < 189) {
                idx++;
//                System.out.println(idx);
            }
            else {
                idx=-1;
                break;
            }
            try {
                Thread.sleep(5);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        }
    }


}
